# Generated by Django 5.1.6 on 2025-03-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
    ]
