# Generated by Django 5.1.6 on 2025-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_aboutcollege_aboutpreviousvitopia_wishlist_tshirt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcollege',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutpreviousvitopia',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
