# Generated by Django 5.1.6 on 2025-03-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_cart_quantity_alter_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tshirt',
        ),
    ]
