# Generated by Django 5.1.6 on 2025-03-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_tshirt_ordered_date_cart_tshirt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='ordered_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
