# Generated by Django 5.1.6 on 2025-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_tshirt_ordered_date_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sports_images/')),
                ('joining_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('winning_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
