# Generated by Django 5.1.6 on 2025-03-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_sport_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedevent',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
