# Generated by Django 5.1.6 on 2025-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_bookedevent_payment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Sport', 'verbose_name_plural': 'Sports'},
        ),
        migrations.AddField(
            model_name='sport',
            name='name',
            field=models.CharField(default='Unknown Sport', max_length=255, unique=True, verbose_name='Sport Name'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(default='sports_images/default_sport.jpg', upload_to='sports_images/'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='joining_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Joining Fee'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='winning_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Winning Prize'),
        ),
    ]
